apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: dev
    app.kubernetes.io/component: deployment.yada
    app.kubernetes.io/instance: yada-dev
    app.kubernetes.io/name: yada-dev
    yada/component: yada
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev
  template:
    metadata:
      labels:
        app: dev
        app.kubernetes.io/component: deployment.yada
        app.kubernetes.io/instance: yada-dev
        app.kubernetes.io/name: yada-dev
        nirmata.io/component: deployment.yada
        yada/component: yada
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
