apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  labels:
    app: yaspirin
    app.kubernetes.io/component: deployment.yada
    app.kubernetes.io/instance: yada-dev
    app.kubernetes.io/name: yada-dev
    yada/component: yada
  name: yada
  namespace: yad-nonprod
  resourceVersion: "433112314"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: yaspirin
      yada/component: yada
    type: RollingUpdate
  template:
      labels:
        app: yaspirin
        app.kubernetes.io/component: deployment.yada
        app.kubernetes.io/instance: yada-dev
        app.kubernetes.io/name: yada-dev
        nirmata.io/component: deployment.yada
        yada/component: yada
    spec:
      containers:
        image: nginx:latest
        name: yada